/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pl_etakt_mobile_networkcompromise_SquaredWrapper */

#ifndef _Included_pl_etakt_mobile_networkcompromise_SquaredWrapper
#define _Included_pl_etakt_mobile_networkcompromise_SquaredWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pl_etakt_mobile_networkcompromise_SquaredWrapper
 * Method:    squared
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_pl_etakt_mobile_networkcompromise_SquaredWrapper_squared
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
